name: Push Docker Image to Docker Hub

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
        # Installs yq and modifies manifests, replacement for sed 
      - name: Install yq and Convert
        run: |
          sudo snap install yq
          yq -i '.spec.template.spec.containers[0].image = "${{ vars.DOCKER_REPO }}:${{ github.sha }}"' deployments/deployment.yaml

        # Needs kubectl installed for k8s-lint
      - name: kubectl CLI Action
        uses: teknatha136/actions-kubectl@v1.0.0
        with:
          kubectl-version: v1.27.3
         
        # Checks Format, Configuration errors, security issues and dry runs inside the K8s cluseter and checks rediness.
#      - uses: azure/setup-kubectl@v2.0
#      - uses: azure/k8s-lint@v1
#        with:
#          lintType: dryrun
#          manifests: |
#             deployments/deployment.yaml


      - name: Clone Private Repository
        uses: actions/checkout@v3
        with:
          repository: namgaytobden/manifest
          token: ${{ secrets.BT_MANIFEST_PULL_PUSH }}
          path: manifest/
          ref: main

      - name: Install yq and Convert
        run: |
          ls
          cd manifest
          ls
