name: Push Docker Image to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Clone Private Repository
        uses: actions/checkout@v3
        with:
<<<<<<< HEAD
          kubectl-version: v1.27.3
         
        # Checks Format, Configuration errors, security issues and dry runs inside the K8s cluseter and checks rediness.
#      - uses: azure/setup-kubectl@v2.0
#      - uses: azure/k8s-lint@v1
#        with:
#          lintType: dryrun
#          manifests: |
#             deployments/deployment.yaml


      - name: Clone Private Repository
        uses: actions/checkout@v3
        with:
=======
>>>>>>> 3380cb9 (Updated: apply manifest workflow)
          repository: namgaytobden/manifest
          token: ${{ secrets.TOKEN }}
          path: manifest/
          ref: main
<<<<<<< HEAD

      - name: Install yq and Convert
        run: |
          ls
          cd manifest
          ls
=======
      
      - name: Lint Action 
        uses: azure/k8s-lint@v2
        with:
          manifests: |
              manifest/deployment/*
          kubeconformOpts: -summary

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v4
        with:
            namespace: testdeploy
            manifests: |
              deployment/mainfest/deployment.yaml
              deployment/mainfest/ingress.yaml
              deployment/mainfest/service.yaml
            images: |
              ${{ vars.DOCKER_REPO }}:${{ github.sha }}
>>>>>>> 3380cb9 (Updated: apply manifest workflow)
