name: Push Docker Image to Docker Hub

on:
  push:
    branches: [ test/lint/yq ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/test-deploy:${{ github.sha }}

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO }}:${{ github.sha }}

      - name: Install yq and Convert
        run: |
             snap install yq
             yq -i '.spec.template.spec.containers[0].image = "${{ vars.DOCKER_USERNAME}}/${{ vars.DOCKER_REPO }}:${{ github.sha }}"' deployment.yaml
    

      - name: kubectl CLI Action
        uses: teknatha136/actions-kubectl@v1.0.0
        with:
          kubectl-version: v1.27.3
      
      - name: Lint Action      
        uses: azure/k8s-lint@v1
        with:
          manifests: |
            deployment.yml
          kubeconformOpts: -summary