name: Push Docker Image to Docker Hub

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Clone Private Repository
        uses: actions/checkout@v3
        with:
          repository: namgaytobden/manifest
          token: ${{ secrets.TOKEN }}
          path: manifest/
          ref: main
      
     # - name: Lint Action 
      #  uses: azure/k8s-lint@v4
       #  manifests: |
         #     manifest/deployment/*
          #kubeconformOpts: -summary

      - uses: namgaytobden/k8s-Manifestation@main
        with:
          manifest_path: manifest/deployment/
          id: image | Deployment | deployment-puma | Certificate
          key: .spec.template.spec.containers[0].image | .metadata.name | .spec.template.spec.imagePullSecrets[0].name | metadata.name
          value: namgaytobden/rails-test3:77 | sucess-test10 | test-12 | test-service

      - name: Check 
        run: | 
          cat manifest/deployment/*
