name: Push Docker Image to Docker Hub

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Clone Private Repository
        uses: actions/checkout@v3
        with:
          repository: namgaytobden/manifest
          token: ${{ secrets.TOKEN }}
          path: manifest/
          ref: main
      
      - name: Lint Action 
        uses: azure/k8s-lint@v2
        with:
          manifests: |
              manifest/deployment/*
          kubeconformOpts: -summary

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v4
        with:
            namespace: testdeploy
            manifests: |
              deployment/mainfest/deployment.yaml
              deployment/mainfest/ingress.yaml
              deployment/mainfest/service.yaml
            images: |
              ${{ vars.DOCKER_REPO }}:${{ github.sha }}