name: Push Docker Image to Docker Hub

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Clone Private Repository
        uses: actions/checkout@v3
        with:
          repository: namgaytobden/manifest
          token: ${{ secrets.TOKEN }}
          path: manifest/
          ref: main
      
     # - name: Lint Action 
      #  uses: azure/k8s-lint@v4
       #  manifests: |
         #     manifest/deployment/*
          #kubeconformOpts: -summary

      - uses: namgaytobden/k8s-manifestation@main
        with:
          image: namgaytobden/rails-test:7744821a249a7a1934c474810229649487da8a04
          manifest_path: manifest/deployment/

      - name: Check 
        run: | 
          cat manifest/deployment/*
          
